spring:
  datasource:
    url: jdbc:mysql://db-oa18v.pub-cdb.ntruss.com:3306/culturelinkdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: user123@

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

spring-boot:
  run:
    jvmArguments: -parameters


logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        transaction: DEBUG
    com:
      .zaxxer: DEBUG
    sql: DEBUG