spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scott
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: scott
    password: tiger

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

spring-boot:
  run:
    jvmArguments: -parameters
