spring:
  datasource:
    url: jdbc:mysql://db-oa18v.pub-cdb.ntruss.com:3306/culturelinkdb

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: user123@

  data:
    mongodb:
      uri: mongodb://winner:1234@localhost:27017/shop2
      database: shop2

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8094

spring-boot:
  run:
    jvmArguments: -parameters


logging:
  level:
    org:
      mybatis: DEBUG
      springframework:
        jdbc: DEBUG
        transaction: DEBUG
    com:
      .zaxxer: DEBUG    
    sql: DEBUG

API-KEY:
  clientKey: c9130d29-65ea-495e-9701-9025010a1b92
  youtubeKey: AIzaSyCBfQCGZ8YfsYLJ7IjYB5xOE5yfIf9L4nY
  naverArticleClientId: 4zTuD9CZkjOkps8VwmC5
  naverArticleClientSecret: FCOaBi2Bcq
  naverClientId: acum3zj3r2

kopis:
  api:
    key: a0cfef9bedc443bc9153b8b024d1b1dc

